using Windows.UI.Xaml;
using System;

namespace Windows.UI.Xaml.Controls
{
    public class DataGridColumn : DependencyObject
    {
        public object Header { get; set; }
        public Style HeaderStyle { get; set; }
        public DataTemplate HeaderTemplate { get; set; }
        public Boolean IsAutoGenerated { get; set; }
        public Boolean IsReadOnly { get; set; }
        public DataGridLength Width { get; set; }
        public Visibility Visibility { get; set; }
    }
}
